# Generated by Django 4.0.4 on 2022-05-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField()),
                ('brand', models.CharField(choices=[('SuperValu', 'SuperValu'), ('Centra', 'Centra'), ('Spar', 'Spar')], max_length=15)),
                ('initials', models.CharField(choices=[('SV', 'SuperValu'), ('CTA', 'Centra'), ('SPAR', 'Spar')], max_length=5)),
                ('name', models.CharField(max_length=5)),
                ('has_deli', models.BooleanField(default=True)),
                ('deli_size', models.CharField(choices=[('Big', 'Department/Store size is Big'), ('Mid', 'Department/Store size is Medium'), ('Small', 'Department/Store size is Small'), ('No', "We don't do that department")], max_length=5)),
                ('has_stockroom', models.BooleanField(default=True)),
                ('stockroom_size', models.CharField(choices=[('Big', 'Department/Store size is Big'), ('Mid', 'Department/Store size is Medium'), ('Small', 'Department/Store size is Small'), ('No', "We don't do that department")], max_length=5)),
                ('no_of_people_in_stockroom', models.IntegerField()),
                ('has_off_licence', models.BooleanField(default=True)),
                ('off_licence_size', models.CharField(choices=[('Big', 'Department/Store size is Big'), ('Mid', 'Department/Store size is Medium'), ('Small', 'Department/Store size is Small'), ('No', "We don't do that department")], max_length=5)),
                ('no_of_people_in_offlicence', models.IntegerField()),
                ('behind_till_size', models.CharField(choices=[('Big', 'Department/Store size is Big'), ('Mid', 'Department/Store size is Medium'), ('Small', 'Department/Store size is Small'), ('No', "We don't do that department")], max_length=5)),
                ('toiletries_size', models.CharField(choices=[('Big', 'Department/Store size is Big'), ('Mid', 'Department/Store size is Medium'), ('Small', 'Department/Store size is Small'), ('No', "We don't do that department")], max_length=5)),
                ('shop_size', models.CharField(choices=[('Big', 'Department/Store size is Big'), ('Mid', 'Department/Store size is Medium'), ('Small', 'Department/Store size is Small'), ('No', "We don't do that department")], max_length=5)),
                ('stock_size_price_range', models.IntegerField(default=None)),
                ('avg_min_crew_size', models.IntegerField(default=None)),
            ],
        ),
    ]
