# Generated by Django 4.0.4 on 2022-05-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shops',
            new_name='Shop',
        ),
    ]
