# Generated by Django 4.0.4 on 2022-05-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_remove_shop_id_alter_shop_shop_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='shop_id',
            new_name='id',
        ),
    ]
