# Generated by Django 4.0.4 on 2022-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=15)),
                ('initials', models.CharField(max_length=5)),
                ('is_supervisor', models.BooleanField(default=True)),
                ('pay_rate', models.IntegerField(default=None)),
                ('has_car', models.BooleanField(default=True)),
            ],
        ),
    ]
