# Generated by Django 4.0.4 on 2022-05-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Experience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('initials', models.CharField(max_length=5)),
                ('no_of_jobs_worked', models.IntegerField(default=None)),
                ('no_years_at_takestock', models.IntegerField(default=None)),
                ('approx_no_of_jobs_done', models.IntegerField(default=None)),
                ('exp_level', models.CharField(choices=[('Expert', 'Expert'), ('Very High', 'Very High'), ('High', 'High'), ('Mid', 'Mid'), ('Low', 'Low')], max_length=15)),
                ('no_of_ctas_worked', models.IntegerField(default=None)),
                ('no_of_svs_worked', models.IntegerField(default=None)),
                ('no_of_sprs_worked', models.IntegerField(default=None)),
                ('do_deli', models.BooleanField(default=True)),
                ('deli_count', models.IntegerField(default=None)),
                ('do_off_licence', models.BooleanField(default=True)),
                ('off_licence_count', models.IntegerField(default=None)),
                ('do_behind_till', models.BooleanField(default=True)),
                ('behind_till_count', models.IntegerField(default=None)),
                ('do_stockroom', models.BooleanField(default=True)),
                ('stockroom_count', models.IntegerField(default=None)),
                ('do_toiletries', models.BooleanField(default=True)),
                ('toiletries_count', models.IntegerField(default=None)),
            ],
        ),
    ]
